Javascript with Interpolation missing semicolon ";" running code without it gives console error "Uncaught TypeError: "Neil deGrasse Tyson" is not a function(..)